---
title: "Kontraste"
author: "Wolfgang Peter"
date: "17 September 2017"
output:
 html_document:
vignette: >
 %\VignetteIndexEntry{Kontraste}
 %\VignetteEngine{knitr::rmarkdown}
 %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(stp25vers)
library(HH)
library(effects)

```

 


```{r}
## The cc176 data comes from Cochran and Cox, page 176
## Cochran, W. G. and Cox, G. M. (1957).
## Experimental Designs, Wiley.


old.contr <- options(contrasts=c("contr.treatment", "contr.treatment"))


data(cc176)

current.levels <- c("galvanic","faradic","60.cycle","25.cycle")
cc176 <-
  data.frame(wt.d=cc176[,1],
             wt.n=cc176[,2],
             n.treats=ordered(rep(c(1,3,6), length=96)),
             current=ordered(rep(rep(current.levels,
                                     rep(3,4)),8), levels=current.levels),
             minutes=ordered(rep(rep(c(1,2,3,5),rep(12,4)), 2)),
             rep=rep(c("I","II"), c(48,48)))
contrasts(cc176$n.treats)
contrasts(cc176$n.treats) <-
  
  contr.poly(3, scores=c(1,3,6))

contrasts(cc176$n.treats)


contrasts(cc176$current) <- "contr.treatment"
contrasts(cc176$n.treats) <- "contr.treatment"


options(old.contr)
#str(cc176)
#cc176 %>% Tabelle2(wt.d, rep, wt.n )

# APA2(~ wt.d + rep + wt.n + n.treats +  current, cc176)

##        Item Characteristics     Statistics
## 1      wt.d                   63.22 (9.72)
## 2       rep               I       50% (48)
## 3                        II       50% (48)
## 4      wt.n                 117.78 (20.75)
## 5  n.treats               1       33% (32)
## 6                         3       33% (32)
## 7                         6       33% (32)
## 8   current        galvanic       25% (24)
## 9                   faradic       25% (24)
## 10                 60.cycle       25% (24)
## 11                 25.cycle       25% (24)
ancovaplot(wt.d ~ wt.n+ current, data=cc176)


cc176.aov <- aov(wt.d ~ rep + wt.n + n.treats + wt.n*current, data=cc176)
summary(cc176.aov)

summary(cc176.aov,
        split=list(n.treats=list(n.treats.lin=1, n.treats.quad=2)),
        expand.split=FALSE)

#windows(8,8)

#plot(allEffects(cc176.aov))
#windows(8,8)


## almost MMC Figure 3, mmc plot of current, default settings for display
 
  cc176.mmc <-
    mmc(cc176.aov, linfct=mcp(current="Tukey",
                              `covariate_average`=TRUE, `interaction_average`=TRUE))
  print(cc176.mmc)
  plot(cc176.mmc)
 


## MMC Figure 3, mmc plot of current, control of display parameters
 
    old.par <- par(mar=c(15,4,4,8)+.1)
    plot(cc176.mmc,  x.offset=1.5,
         iso.name=FALSE, col.iso=16,
         col.mca.signif="red", lty.mca.not.signif=2,
         print.mca=TRUE, print.lmat=FALSE)
    par(old.par)
 



## MMC Figure 4, current with orthogonal contrasts and control of display
cc176.orth <- cbind(  "g-f"=c( 1,-1, 0, 0),
                      "60-25"=c( 0, 0, 1,-1),
                      "gf-AC"=c( 1, 1,-1,-1))
dimnames(cc176.orth)[[1]] <- levels(cc176$current)

 
  cc176.mmc <-
    mmc(cc176.aov,
        linfct=mcp(current="Tukey",
                   `covariate_average`=TRUE, `interaction_average`=TRUE),
        focus.lmat=cc176.orth
    )
  print(cc176.mmc)
  
  
  old.par <- par(mar=c(15,4,4,8)+.1)
  plot(cc176.mmc, x.offset=1.5,
       iso.name=FALSE, col.iso=16,
       col.mca.signif="red", lty.mca.not.signif=2,
       col.lmat.signif="blue", lty.lmat.not.signif=2,
       print.mca=FALSE, print.lmat=TRUE)
  par(old.par)
 



## MMC Figure 10, current, pairwise and orthogonal contrasts
 
    old.par <- par(mar=c(15,4,4,8)+.1)
    plot(cc176.mmc,  x.offset=1.5,
         iso.name=FALSE, col.iso=16,
         col.mca.signif="red", lty.mca.not.signif=2,
         col.lmat.signif="blue", lty.lmat.not.signif=2,
         print.mca=TRUE, print.lmat=TRUE)
    par(old.par)
 



```

